GarmentsManagementApp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'GarmentsManagementApp'
urlpatterns = [
    path('',views.home),
    path('login/',views.admin_login,name='login'),
    path('logout/',views.admin_logout,name='logout'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('addEmployee/',views.AddEmployee,name='AddEmployee'),
    path('employees/',views.ShowEmployees,name='ShowEmployee'),
    path('editEmployee/<int:pk>/',views.EditEmployee,name='editEmployee'),
    path('deleteEmployee/<int:pk>/',views.deleteEmployee,name='deleteEmployee'),

    path('createproduct/',views.AddProduct,name='AddProduct'),
    path('ShowProducts/',views.ShowProducts,name='ShowProducts'),
    path('editProduct/<int:pk>/',views.editProduct,name='editProduct'),
    path('deleteProduct/<int:pk>/',views.deleteProduct,name='deleteProduct'),

    path('addGarment/',views.AddGarment,name='AddGarment'),
    path('ShowGarments/',views.ShowGarments,name='ShowGarments'),
    path('editGarment/<int:pk>/',views.EditGarment,name='editGarment'),
    path('deleteGarment/<int:pk>/',views.deleteGarment,name='deleteGarment'),

    path('createorder/',views.createOrder,name='createOrder'),
    path('showorders/',views.ShowOrders,name='ShowOrders'),
    path('deleteOrder/<int:pk>/', views.deleteOrder, name='deleteOrder'),
    path('forward/<int:pk>/',views.forward,name='forwardOrder'),
    path('reject/<int:pk>/',views.reject,name='rejectOrder'),
    path('showdepartments/',views.showdepartments,name='ShowDepartments'),
    path('showSuppliers/',views.showSuppliers,name='ShowSuppliers'),
    path('showShipments/',views.showShipments,name='showShipments'),
    path('calculateDate/',views.calculateDeliveryDate,name='calculateDate'),

    path('reset_password/',
         auth_views.PasswordResetView.as_view(template_name="GarmentsManagementApp/password_reset.html"),
         name="reset_password"),

    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(template_name="GarmentsManagementApp/password_reset_sent.html"),
         name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="GarmentsManagementApp/password_reset_form.html"),
         name="password_reset_confirm"),

    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name="GarmentsManagementApp/password_reset_done.html"),
         name="password_reset_complete")
]

GarmentsProject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('',include('GarmentsManagementApp.urls')),
    path('admin', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/AddGarment.html
{% extends 'index.html' %}
{% block content %}
    <div align="center">
    <br><br><br><br><br><br><br><br>
        <form method="POST">
            {% csrf_token %}
            <label for="name"> Name </label>
            <input type="text" name="name" id="name" required="true"><br><br>
            <label for="type"> Type</label>
            <input type="text" name="type" id="type" required="true"><br><br>
            <input type="submit">
        </form>
    </div>
{% endblock %}

templates/EditEmployee.html
{% extends 'index.html' %}
{% block content %}
    <div align="center">
    <br><br><br><br><br><br><br><br>
        <form method="POST" action="/editEmployee/{{ data.id }}/">
            {% csrf_token %}
            <label for="name"> Name </label>
            <input type="text" name="name" id="name" required="true" value="{{ data.Name }}"><br><br>
            <label for="department"> department</label>
            <select name="department" id="department" required="true">
               {% for item in depts %}
                   <option value= {{ item.id }} > {{ item.Name }} </option>
                {% endfor %}
            </select><br><br>
            <label for="salary"> Salary</label>
            <input type="number" name="salary" id="salary" required="true" value="{{ data.salary }}"><br><br>

            <input type="text" name="phone" id="phone" required="true" value="{{ data.Phone }}"><br><br>
            <label for="address"> Address </label>
            <input type="text" name="address" id="address" required="true" value="{{ data.address }}"><br><br>
            <label for="status"> Status </label>
            <input type="text" name="status" id="status" required="true" value="{{ data.status }}"><br><br>

            <input type="submit" value="Update">
        </form>
    </div>
{% endblock %}

templates/EditGarment.html
{% extends 'index.html' %}
{% block content %}
    <div align="center">
    <br><br><br><br><br><br><br><br>
        <form method="POST" >
            {% csrf_token %}
            <label for="name"> Name </label>
            <input type="text" name="name" id="name" required="true" value="{{ data.name }}"><br><br>
             <label for="type"> Type</label>
            <input type="text" name="type" id="type" required="true" value="{{ data.type }}"><br><br>
            <input type="submit" value="Update">
        </form>
    </div>
{% endblock %}

templates/HomePage.html
{% extends 'index.html' %}
{% block content %}
<h2>This is Home Page</h2>

{% endblock %}

templates/ShowEmployees.html
{% extends 'index.html' %}
{% block content %}
    <style>
#customers {
  font-family: Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#customers td, #customers th {
  border: 1px solid #ddd;
  padding: 8px;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #26a5b6;
  color: white;
}
</style>

<div align="center">
    <form method="POST">
        {% csrf_token %}
        <br><br><br><br>
        <label for="searchname"> Search Employee </label>
        <input type="text" name="searchname" id="searchname" placeholder="Enter Employee Name">
        <input type="submit" value="Search">
    </form>
</div>

<div align="center">
    <form method="POST">
        {% csrf_token %}
        <br><br>
        <label for="searchid"> Search Employee </label>
        <input type="text" name="searchid" id="searchid" placeholder="Enter Employee id">
        <input type="submit" value="Search"><br><br><br>
    </form>
</div>
<table id="customers">
  <tr>
      <th>Id</th>
    <th>Name</th>
    <th>Department</th>
    <th>Salary</th>
      <th>Phone No</th>
      <th>Address</th>
      <th>Status</th>
      <th>Action</th>
  </tr>

    {% for item in list %}
        <tr>
        <td>{{ item.EmployeeID }}</td>
            <td>{{ item.Name }}</td>
            <td>{{ item.department.Name }}</td>
            <td>{{ item.salary }}</td>
            <td>{{ item.Phone }}</td>
            <td>{{ item.address }}</td>
            <td>{{ item.status }}</td>
            <td> <a type="button" class="alert-dark" href="{% url 'GarmentsManagementApp:editEmployee' pk=item.id %}">Edit    [] </a> <a type="button" class="alert-danger" href="{% url 'GarmentsManagementApp:deleteEmployee' pk=item.id %}" onclick="alert('Are you sure?')">Delete</a></td>
        </tr>
    {% endfor %}


</table>
{% endblock %}

templates/ShowGarments.html
{% extends 'index.html' %}
{% block content %}
    <style>
#customers {
  font-family: Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#customers td, #customers th {
  border: 1px solid #ddd;
  padding: 8px;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #26a5b6;
  color: white;
}
</style>


<table id="customers">
  <tr>

    <th>Id</th>
    <th>Name</th>
    <th>Type</th>
      <th>Action</th>
  </tr>

    {% for item in list %}
        <tr>
            <td>{{ item.id }}</td>
            <td>{{ item.name }}</td>
            <td>{{ item.type }}</td>

            <td> <a type="button" class="alert-dark" href="{% url 'GarmentsManagementApp:editGarment' pk=item.id %}">Edit    [] </a> <a type="button" class="alert-danger" href="{% url 'GarmentsManagementApp:deleteGarment' pk=item.id %}" onclick="alert('Are you sure?')">Delete</a></td>
        </tr>
    {% endfor %}


</table>
{% endblock %}

templates/ShowOrders.html
{% extends 'index.html' %}
{% block content %}
    <style>
#customers {
  font-family: Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#customers td, #customers th {
  border: 1px solid #ddd;
  padding: 8px;
    text-align: center;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers button {
    background-color: #50c764
}

#customers th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: center;
  background-color: #26a5b6;
  color: white;
}
</style>
</head>
<body>

<table id="customers">
  <tr>
      <th>OrderID</th>
    <th>Customer Name</th>
    <th>Phone</th>
    <th>Product Name</th>
      <th>Product Description</th>
      <th>Garments Name</th>
      <th>Status</th>
      <th>Department</th>
      <th>Quantity</th>
      <th>Total Price</th>
      <th>Action</th>
  </tr>

    {% for item in list %}
        <tr>
            <td>{{ item.OrderID }}</td>
            <td>{{ item.CustomerName}}</td>
            <td>{{ item.CustomerPhn }}</td>
            <td>{{ item.product.Name }}</td>
            <td>{{ item.product.description }}</td>
            <td>{{ item.product.garment.name }}</td>
            <td>{{ item.Status }}</td>
            <td>{{ item.department.Name }}</td>
            <td>{{ item.quantity }}</td>
            <td>{{ item.TotalPrice }}</td>
            <td>  <a type="button" class="alert-danger" href="{% url 'GarmentsManagementApp:deleteOrder' pk=item.id  %}" onclick="alert('Are you sure?')">Delete</a> <br>

            {% if item.Status != 'Shipped' %}
                    <a type="button" class="alert-danger" href="{% url 'GarmentsManagementApp:forwardOrder' pk=item.id  %}" onclick="alert('Are you sure?')">Forward to Next Dept.</a><br>
               {% if item.department.Name != 'Production' %}
                <a type="button" class="alert-danger" href="{% url 'GarmentsManagementApp:rejectOrder' pk=item.id  %}" onclick="alert('Are you sure?')">Send Back to Prev. Dept.</a>
                {% endif %}
            {% endif %}
            </td>
        </tr>
    {% endfor %}


</table>
{% endblock %}

templates/calculateDelivery.html
{% extends 'index.html' %}
{% block content %}

    <style>
    #data {
            font-family: Arial, Helvetica, sans-serif;
            border-collapse: collapse;
            width: 100%;
        font-size: xx-large;
        }
    </style>
    <div align="center">
        <br><br><br><br><br><br><br><br>
        <form method="POST">
            {% csrf_token %}

            <label for="product"> Product </label>
            <select name="product" id="product" required="true">
                {% for i in products %}
                <option value="{{ i.id }}">{{ i.Name }} |Garment:- {{ i.garment.name }}|Description:- {{ i.description }}|Price:-{{ i.price }}</option>
                {% endfor %}
                </select><br><br>
            <label for="quant"> Enter Quantity</label>
            <input type="number" name="quant" id="quant" required="true" ><br><br>
            <br><br>
            <input type="submit" value="Calculate">
        <br><br><br>
        <label for="data"> Estimated shipment date : </label>
        <div id="data">
            {{ delivarydate }}
        </div>
        </form>
    </div>




{% endblock %}

templates/createOrder.html
{% extends 'index.html' %}
{% block content %}
    <div align="center">
    <br><br><br><br><br><br><br><br>
        <form method="POST">
            {% csrf_token %}
            <label for="customer_name">Customer Name </label>
            <input type="text" name="customer_name" id="customer_name" required="true"><br><br>

            <label for="OrdId"> Order Id </label>
            <input type="text" name="OrdId" id="OrdId" required="true"><br><br>

            <label for="customer_phn">Customer Phone </label>
            <input type="text" name="customer_phn" id="customer_phn" required="true"><br><br>

            <select name="product" id="product" required="true">
                {% for i in list %}
                <option value="{{ i.id }}">{{ i.Name }} |Garment:- {{ i.garment.name }}|Description:- {{ i.description }}|Price:-{{ i.price }}</option>
                {% endfor %}
                </select><br><br>

            <label for="quantity"> Quantity</label>
            <input type="number" name="quantity" id="quantity" required="true"><br><br>
            <input type="submit">
        </form>
    </div>
{% endblock %}

templates/index.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Garments Management</title>
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href=" {% static 'assets/fonts/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/Footer-Basic.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <link rel="stylesheet" href="{% static 'assets/css/Navigation-Clean.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">
    <link rel="icon" size="32x32" href="{% static 'assets/imgicon.png' %}">
</head>

<body>
<nav class="navbar navbar-light navbar-expand-md text-monospace text-nowrap text-truncate navigation-clean">
    <div class="container"><a
            class="navbar-brand text-monospace text-nowrap text-truncate text-break text-dark flash animated" href="#">Garments
        Management Shop</a>
        <button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span
                class="navbar-toggler-icon"></span></button>
        <div
                class="collapse navbar-collapse bounce animated" id="navcol-1">
            <ul class="nav navbar-nav ml-auto">
                <li class="nav-item" role="presentation"><a class="nav-link" data-bs-hover-animate="pulse"
                                                            href="/">Home</a></li>
                {% if user.is_authenticated %}
                    <li class="nav-item" role="presentation"><a class="nav-link" data-bs-hover-animate="pulse"
                                                                href="/dashboard/">Dashboard</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" data-bs-hover-animate="pulse"
                                                                href="/logout/">Logout</a></li>
                {% else %}
                    <li class="nav-item" role="presentation"><a class="nav-link" data-bs-hover-animate="pulse"
                                                                href="/login/">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>



{% block content %}
{% endblock %}




<div class="footer-basic">
    <footer>
        <div class="social"><a href="#"><i class="icon ion-social-instagram"></i></a><a href="#"><i
                class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a
                href="https://www.facebook.com/"><i class="icon ion-social-facebook"></i></a></div>
        <ul class="list-inline">
            <li class="list-inline-item"><a href="#">Home</a></li>
            <li class="list-inline-item"><a href="#">Services</a></li>
            <li class="list-inline-item"><a href="#">About</a></li>
            <li class="list-inline-item"><a href="#">Terms</a></li>
            <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
        </ul>
        <p class="copyright">Company Name © 2020</p>
    </footer>
</div>
<script src="{% static 'assets/js/jquery.min.js' %}"></script>
<script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/bs-init.js' %}"></script>
</body>

</html>

templates/login.html
{% extends 'index.html' %}
{% block content %}
<br><br><br><br><br><br><br><br><br>
    <div align="center">

    <form method="POST">
         {% csrf_token %}
        <label for="id_username"> Enter Username </label>
        <input type="text" name="username" id="id_username" placeholder="UserName"> <br><br>
        <label for="id_pass"> Enter password</label>
        <input type="password" name="password" id="id_pass" placeholder="password"><br><br>
        <input type="submit">
    </form>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
    <br><br><br>
</div>
{% endblock %}

templates/password_reset.html
<h3>Password reset</h3>

<p>Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.</p>

<form method="POST">

	{% csrf_token %}
	{{form}}
	<input type="Submit" name="Send email">

</form>

templates/password_reset_done.html
<h3>Password reset complete</h3>

<p>Your password has been set. You may go ahead and log in now.</p>

<a href="/">Log in</a>

templates/password_reset_sent.html
<h3>Password reset sent</h3>


<p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>

<p>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</p>